version: '3'

services:
  frontend: 
    build: 
      context: ./thesis_frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
      
  backend:
    privileged: true 
    build: 
      context: ./thesis_backend
      dockerfile: Dockerfile-flask
    ports:
      - "8000:8000"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - /dev/ttyS0:/dev/ttyS0
    depends_on:
      - rabbitmq
      - mongodb

  mongodb: 
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    volumes: 
      - "mongodb-data:/data/db"

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    privileged: true
    build: 
      context: ./thesis_backend
      dockerfile: Dockerfile-celery
    depends_on:
      - rabbitmq
      - mongodb
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    command: celery -A run.celery worker --loglevel=info
      
volumes:
  mongodb-data:
