FROM python:3.9-slim

WORKDIR /app

COPY avaspecx64.dll /app/


COPY requirements.txt requirements.txt


RUN pip install --no-cache-dir -r requirements.txt

COPY . . 

CMD ["gunicorn", "run:app", "-b", "0.0.0.0:8000"]

